[ollama]
i-0ddc0782cf46ed7be ansible_aws_ssm_instance_id=i-0ddc0782cf46ed7be private_ip=10.0.20.112

[openwebui]
i-08a79e1fdabbf1c4c ansible_aws_ssm_instance_id=i-08a79e1fdabbf1c4c ollama_api_url=http://10.0.20.112:11434

[ai-platform:children]
ollama
openwebui

[all:vars]
ansible_connection=amazon.aws.aws_ssm
ansible_aws_ssm_region=ap-south-1
ansible_aws_ssm_bucket_name=kdsingh-terraform-state
ansible_aws_ssm_profile=default