---
- name: Install required packages
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
    state: present

- name: Create OpenWebUI user
  user:
    name: "{{ openwebui_user }}"
    system: yes
    create_home: no

- name: Create installation directory
  file:
    path: "{{ openwebui_home }}"
    state: directory
    owner: "{{ openwebui_user }}"
    group: "{{ openwebui_user }}"
    mode: "0755"

- name: Create virtual environment
  command:
    cmd: python3 -m venv {{ openwebui_home }}/venv
    creates: "{{ openwebui_home }}/venv"

- name: Install OpenWebUI
  pip:
    name: open-webui
    virtualenv: "{{ openwebui_home }}/venv"
    state: latest